# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  location: 'France Central'
  locationshort: francecentral
  region: 'frc'
  workingDirectory: '$(System.DefaultWorkingDirectory)/ecommerce/src'
  outputDirectory: '$(System.DefaultWorkingDirectory)/publish_output'

trigger:
  branches:
    include: 
      - master
  paths:
    include:
      - ecommerce

pool:
  vmImage: 'windows-latest'

stages: 
  - stage: Build
    jobs: 
    - job: Build
      steps: 
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet 5.5'
        inputs:
          versionSpec: 5.5
    
      - task: NuGetCommand@2
        displayName: 'NuGet restore */.sln'
        
      - task: VSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: '$(workingDirectory)/**/Relecloud.Web.csproj'
          vsVersion: '16.0'
          msbuildArgs: '-p:OutputPath=$(outputDirectory)'
          configuration: 'Debug'
          clean: true

      - publish: $(outputDirectory)
        artifact: WebApp

  - stage: DeployDev
    dependsOn: Build
    condition: succeeded()
    jobs: 
    - job: DeployInfra
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'create resource group'
        inputs:
          deploymentScope: 'Subscription'
          azureResourceManagerConnection: 'Azure CXP FTA Internal Subscription givermei(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
          subscriptionId: '49e23c68-dee0-4c5b-8c21-74acea0a2662'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: 'ecommerce/deploy/azuredeploy.rg.json'
          overrideParameters: '-name demo-fta-ecommerce -env dev -location $(locationshort) -region $(region)'
          deploymentMode: 'Incremental'

      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'deploy resources'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Azure CXP FTA Internal Subscription givermei(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
          subscriptionId: '49e23c68-dee0-4c5b-8c21-74acea0a2662'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'demo-fta-ecommerce-$(region)-dev'
          location: '$(location)'
          templateLocation: 'Linked artifact'
          csmFile: 'ecommerce/deploy/azuredeploy.app.json'
          overrideParameters: '-name demo-fta-ecommerce -env dev -prefix gitte -region $(region) -sqlDatabaseAdministratorLogin theadmin -sqlDatabaseAdministratorPassword $(SQLPW)'
          deploymentMode: 'Incremental'

    - job: DeployApp
      dependsOn: DeployInfra
      condition: succeeded()
      steps:
      - download: current
        artifact: WebApp

      - task: AzureWebApp@1
        displayName: 'deploy Relecloud web app'
        inputs:
          azureSubscription: 'Azure CXP FTA Internal Subscription givermei(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
          appType: 'webApp'
          appName: 'gitte-demo-fta-ecommerce-wa-$(region)-dev'
          package: '$(Pipeline.Workspace)/WebApp/**/*.*'
          deploymentMethod: 'auto'
