# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: 
      - master
  paths:
    include:
      - ecommerce
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'ecommerce/deploy'
    Contents: '**.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/arm'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Azure CXP FTA Internal Subscription givermei(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
    subscriptionId: '49e23c68-dee0-4c5b-8c21-74acea0a2662'
    location: 'South Africa North'
    templateLocation: 'Linked artifact'
    csmFile: '$(build.artifactstagingdirectory)/arm'
    overrideParameters: '-name gitte-fta-ecommerce -env dev -location southafricanorth'
    deploymentMode: 'Incremental'
